### ISSUE TITLE
Screen refresh rate is extremely slow

### ISSUE THREAD

**Issue by shekit** [UCTRONICS/UCTRONICS_LCD35_RPI#1]
Is it possible to increase the refresh rate of the screen? I just purchased this screen off amazon and its impossible to view a video on it. There is a big swipe across the screen as the video transitions through each frame.

**Comment by UCTRONICS** [comment]
@shekit,
Hi,
The SPI speed has reached 32MHZ,
This screen can't support the video if the rate of frame is to big.

Regards,

**Comment by falcon609** [comment]
The same thing happened to me. When I ordered the screen off amazon, it said that it supported games and videos, which it does not at all. The videos I am trying to watch are from youtube, the biggest video sharing website, so if it isn't compatible with that, some sort of fix should be made. It is a great screen otherwise though!

**Comment by picamproject** [comment]
Videos don't work! Please fix this!

**Comment by UCTRONICS** [comment]
dimensions are not significantly different, each has advantages.
2. The experimental research conclusions based on PBL teaching mode are as follows:
① After the experiment, the critical thinking of the students in the experimental class was improved significantly（P=0.001<0.01）, It shows that PBL teaching can promote students' critical thinking tendency, promoting systematic ability, confidence, and cognitive maturity.
② There are differences in the promoting effect of teaching on the critical thinking tendency of boys and girls, promote boys to find them, be more confident. The improvement of truth-seeking and self- confidence of boys and the systematized ability of girls.
The teaching strategies adopted in this paper have no promoting effect on other dimensions of critical thinking tendency, and the reasons need to be further explored.
