### ISSUE TITLE
Cannot select resolution from raspi-config 

### ISSUE THREAD

**Issue by geophpherie** [UCTRONICS/UCTRONICS_LCD35_RPI#9]
I just installed the driver for this display as instructed.Using the Raspberry Pi Configuration GUI, I can selection the resolution installed by the driver (DMT mode 87 480x320 59Hz 15:9) along with all the typical ones set up by the Pi. However, when using the raspi-config tool at the command line, after navigating from Advanced Options to Resolution and hitting Enter on Resolution, the raspi-config tool exits, flashes the command line screen quick, then re-appears on the main screen. This makes it impossible to change resolution using raspi-config. I don't see any error messages or text to point me as to what may be going wrong. I'm thinking the addition of the new driver / resolution setting might be causing it problems somehow, but I really don't know. Any thoughts?

**Comment by UCTRONICS** [comment]
@jbeyer16 
We have forced the system to display in 480x320 resolution in order to suitable for our screen.
The screen in 3.5 inch doesn't support other resolutions.

**Comment by geophpherie** [comment]
I understand that. And it works fine. However, the menu from raspi-config no longer appears to select any resolution, including the correct one. I contacted the people at raspi-config about it and they asked me to contact you all.
